services:
  api:
    build:
      context: backend
      target: builder
    container_name: mafia-online-party-game-fastapi
    image: mafia-online-party-game-api
    ports:
      - '${BACKEND_PORT}:8000'
    restart: "no"
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: runtime
      args:
        VITE_WEBSOCKET_URL: ${VITE_WEBSOCKET_URL}
    container_name: mafia-online-party-game-web
    image: mafia-online-party-game-web
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NODE_ENV: production
